<a href="https://colab.research.google.com/github/leman-cap13/phobia-quiz-/blob/main/CreditScore.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [187]:
import pandas as pd
import numpy as np

In [188]:
! kaggle datasets download -d parisrohan/credit-score-classification

Dataset URL: https://www.kaggle.com/datasets/parisrohan/credit-score-classification
License(s): CC0-1.0
credit-score-classification.zip: Skipping, found more recently modified local copy (use --force to force download)

In [189]:
!unzip /content/credit-score-classification.zip

Archive:  /content/credit-score-classification.zip
replace test.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: no
replace train.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: yes
  inflating: train.csv

In [190]:
df=pd.read_csv('/content/train.csv')
df

<ipython-input-190-dbdb7da5ae7e>:1: DtypeWarning: Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('/content/train.csv')

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,0x1602,CUS_0xd40,January,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,_,809.98,26.822620,22 Years and 1 Months,No,49.574949,80.41529543900253,High_spent_Small_value_payments,312.49408867943663,Good
1,0x1603,CUS_0xd40,February,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,31.944960,NaN,No,49.574949,118.28022162236736,Low_spent_Large_value_payments,284.62916249607184,Good
2,0x1604,CUS_0xd40,March,Aaron Maashoh,-500,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,28.609352,22 Years and 3 Months,No,49.574949,81.699521264648,Low_spent_Medium_value_payments,331.2098628537912,Good
3,0x1605,CUS_0xd40,April,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,31.377862,22 Years and 4 Months,No,49.574949,199.4580743910713,Low_spent_Small_value_payments,223.45130972736786,Good
4,0x1606,CUS_0xd40,May,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,Good,809.98,24.797347,22 Years and 5 Months,No,49.574949,41.420153086217326,High_spent_Medium_value_payments,341.48923103222177,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,0x25fe9,CUS_0x942c,April,Nicks,25,078-73-5990,Mechanic,39628.99,3359.415833,4,...,_,502.38,34.663572,31 Years and 6 Months,No,35.104023,60.97133255718485,High_spent_Large_value_payments,479.866228,Poor
99996,0x25fea,CUS_0x942c,May,Nicks,25,078-73-5990,Mechanic,39628.99,3359.415833,4,...,_,502.38,40.565631,31 Years and 7 Months,No,35.104023,54.18595028760385,High_spent_Medium_value_payments,496.65161,Poor
99997,0x25feb,CUS_0x942c,June,Nicks,25,078-73-5990,Mechanic,39628.99,3359.415833,4,...,Good,502.38,41.255522,31 Years and 8 Months,No,35.104023,24.02847744864441,High_spent_Large_value_payments,516.809083,Poor
99998,0x25fec,CUS_0x942c,July,Nicks,25,078-73-5990,Mechanic,39628.99,3359.415833,4,...,Good,502.38,33.638208,31 Years and 9 Months,No,35.104023,251.67258219721603,Low_spent_Large_value_payments,319.164979,Standard
99999,0x25fed,CUS_0x942c,August,Nicks,25,078-73-5990,Mechanic,39628.99_,3359.415833,4,...,Good,502.38,34.192463,31 Years and 10 Months,No,35.104023,167.1638651610451,!@9#%8,393.673696,Poor

In [191]:
df.isna().sum()

ID                              0
Customer_ID                     0
Month                           0
Name                         9985
Age                             0
SSN                             0
Occupation                      0
Annual_Income                   0
Monthly_Inhand_Salary       15002
Num_Bank_Accounts               0
Num_Credit_Card                 0
Interest_Rate                   0
Num_of_Loan                     0
Type_of_Loan                11408
Delay_from_due_date             0
Num_of_Delayed_Payment       7002
Changed_Credit_Limit            0
Num_Credit_Inquiries         1965
Credit_Mix                      0
Outstanding_Debt                0
Credit_Utilization_Ratio        0
Credit_History_Age           9030
Payment_of_Min_Amount           0
Total_EMI_per_month             0
Amount_invested_monthly      4479
Payment_Behaviour               0
Monthly_Balance              1200
Credit_Score                    0
dtype: int64

In [192]:
df=df.drop(['Month','Name','ID','Customer_ID','SSN','Type_of_Loan','Monthly_Inhand_Salary'],axis=1)
df

,Age,Occupation,Annual_Income,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,Changed_Credit_Limit,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,23,Scientist,19114.12,3,4,3,4,3,7,11.27,...,_,809.98,26.822620,22 Years and 1 Months,No,49.574949,80.41529543900253,High_spent_Small_value_payments,312.49408867943663,Good
1,23,Scientist,19114.12,3,4,3,4,-1,NaN,11.27,...,Good,809.98,31.944960,NaN,No,49.574949,118.28022162236736,Low_spent_Large_value_payments,284.62916249607184,Good
2,-500,Scientist,19114.12,3,4,3,4,3,7,_,...,Good,809.98,28.609352,22 Years and 3 Months,No,49.574949,81.699521264648,Low_spent_Medium_value_payments,331.2098628537912,Good
3,23,Scientist,19114.12,3,4,3,4,5,4,6.27,...,Good,809.98,31.377862,22 Years and 4 Months,No,49.574949,199.4580743910713,Low_spent_Small_value_payments,223.45130972736786,Good
4,23,Scientist,19114.12,3,4,3,4,6,NaN,11.27,...,Good,809.98,24.797347,22 Years and 5 Months,No,49.574949,41.420153086217326,High_spent_Medium_value_payments,341.48923103222177,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,25,Mechanic,39628.99,4,6,7,2,23,7,11.5,...,_,502.38,34.663572,31 Years and 6 Months,No,35.104023,60.97133255718485,High_spent_Large_value_payments,479.866228,Poor
99996,25,Mechanic,39628.99,4,6,7,2,18,7,11.5,...,_,502.38,40.565631,31 Years and 7 Months,No,35.104023,54.18595028760385,High_spent_Medium_value_payments,496.65161,Poor
99997,25,Mechanic,39628.99,4,6,5729,2,27,6,11.5,...,Good,502.38,41.255522,31 Years and 8 Months,No,35.104023,24.02847744864441,High_spent_Large_value_payments,516.809083,Poor
99998,25,Mechanic,39628.99,4,6,7,2,20,NaN,11.5,...,Good,502.38,33.638208,31 Years and 9 Months,No,35.104023,251.67258219721603,Low_spent_Large_value_payments,319.164979,Standard
99999,25,Mechanic,39628.99_,4,6,7,2,18,6,11.5,...,Good,502.38,34.192463,31 Years and 10 Months,No,35.104023,167.1638651610451,!@9#%8,393.673696,Poor

In [193]:
df['Age'] = df['Age'].replace('_', '', regex = True)
df['Age'] = df['Age'].astype(int)
df = df[(df['Age'] <= 101) & (df['Age'] >= 18)]

In [194]:
df.loc[:,'Annual_Income'] = df['Annual_Income'].replace('_', '', regex = True)
df.loc[:,'Annual_Income'] = df['Annual_Income'].astype(float)
df['Annual_Income']

0        19114.12
1        19114.12
3        19114.12
4        19114.12
5        19114.12
           ...
99995    39628.99
99996    39628.99
99997    39628.99
99998    39628.99
99999    39628.99
Name: Annual_Income, Length: 91518, dtype: object

In [195]:
df.loc[:,'Num_of_Loan']=df['Num_of_Loan'].replace('_', '', regex = True)
df.loc[:,'Num_of_Loan']=df['Num_of_Loan'].astype(int)
df['Num_of_Loan']

0        4
1        4
3        4
4        4
5        4
        ..
99995    2
99996    2
99997    2
99998    2
99999    2
Name: Num_of_Loan, Length: 91518, dtype: object

In [196]:
df['Credit_History_Age']=df['Credit_History_Age'].str.replace('Years', '').str.replace('Months', '').str.replace('and', '').str.strip()
#str.replace(r'\s+', '') remove aa whitespace
# df['Credit_History_Age']=df['Credit_History_Age'].str.replace(r'\s+', '')
df['Credit_History_Age']=df['Credit_History_Age'].str.replace(' ','')

df['Credit_History_Age']

<ipython-input-196-97eb5baf5d95>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Credit_History_Age']=df['Credit_History_Age'].str.replace('Years', '').str.replace('Months', '').str.replace('and', '').str.strip()
<ipython-input-196-97eb5baf5d95>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Credit_History_Age']=df['Credit_History_Age'].str.replace(' ','')

0         221
1         NaN
3         224
4         225
5         226
         ...
99995     316
99996     317
99997     318
99998     319
99999    3110
Name: Credit_History_Age, Length: 91518, dtype: object

In [197]:
df.loc[:,'Credit_History_Age']=df['Credit_History_Age'].astype(float)
df.loc[:,'Credit_History_Age'].fillna(df['Credit_History_Age'].median(), inplace=True)
df['Credit_History_Age']

<ipython-input-197-94df21782f5f>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.loc[:,'Credit_History_Age'].fillna(df['Credit_History_Age'].median(), inplace=True)
<ipython-input-197-94df21782f5f>:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.loc[:,'Credit_History_Age'].fillna(df['Credit_History_Age'].median(), inplace=True)
<ipython-input-197-94df21782f5f>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:,'Credit_History_Age'].fillna(df['Credit_History_Age'].median(), inplace=True)

0         221.0
1         209.0
3         224.0
4         225.0
5         226.0
          ...
99995     316.0
99996     317.0
99997     318.0
99998     319.0
99999    3110.0
Name: Credit_History_Age, Length: 91518, dtype: float64

In [198]:
df.loc[:,'Payment_Behaviour']=df['Payment_Behaviour'].str.replace('_', ' ',regex=True)
df.loc[:,'Payment_Behaviour']=df['Payment_Behaviour'].str.strip('!@9#%8')

In [199]:
df['Payment_Behaviour']

0         High spent Small value payments
1          Low spent Large value payments
3          Low spent Small value payments
4        High spent Medium value payments
5
                       ...
99995     High spent Large value payments
99996    High spent Medium value payments
99997     High spent Large value payments
99998      Low spent Large value payments
99999
Name: Payment_Behaviour, Length: 91518, dtype: object

In [200]:
df['Payment_Behaviour'].str.contains(r'[^a-zA-Z0-9]').sum()

84594

In [201]:
df.loc[:, 'Num_of_Delayed_Payment'] = df['Num_of_Delayed_Payment'].replace('_', '', regex=True)
df['Num_of_Delayed_Payment']=df['Num_of_Delayed_Payment'].astype(float)
df.loc[:,'Num_of_Delayed_Payment']=df['Num_of_Delayed_Payment'].fillna(df['Num_of_Delayed_Payment'].median())
df['Num_of_Delayed_Payment'].isna().sum()

<ipython-input-201-524e52b2b1a6>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Num_of_Delayed_Payment']=df['Num_of_Delayed_Payment'].astype(float)

0

In [202]:
df.loc[:, 'Outstanding_Debt']=df['Outstanding_Debt'].replace('_','',regex=True)
df['Outstanding_Debt']=df['Outstanding_Debt'].astype(float)

<ipython-input-202-e9c98da7c12d>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Outstanding_Debt']=df['Outstanding_Debt'].astype(float)

In [203]:
df.loc[:,'Amount_invested_monthly']=df['Amount_invested_monthly'].replace('_','',regex=True)
df.loc[:,'Amount_invested_monthly']=df['Amount_invested_monthly'].astype(float)
df.loc[:,'Amount_invested_monthly']=df['Amount_invested_monthly'].fillna(df['Amount_invested_monthly'].median())

<ipython-input-203-132b995dfcde>:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.loc[:,'Amount_invested_monthly']=df['Amount_invested_monthly'].fillna(df['Amount_invested_monthly'].median())

In [204]:
df.loc[:,'Monthly_Balance']=df['Monthly_Balance'].replace('_','',regex=True)
df['Monthly_Balance']=df['Monthly_Balance'].astype(float)

<ipython-input-204-dce86b9cfd95>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Monthly_Balance']=df['Monthly_Balance'].astype(float)

In [205]:
df.loc[:,'Monthly_Balance']=df['Monthly_Balance'].fillna(df['Monthly_Balance'].median())
df['Monthly_Balance'].isna().sum()

0

In [206]:
df.loc[:, 'Num_Credit_Inquiries']=df['Num_Credit_Inquiries'].fillna(df['Num_Credit_Inquiries'].median())
df['Num_Credit_Inquiries']

0        4.0
1        4.0
3        4.0
4        4.0
5        4.0
        ...
99995    3.0
99996    3.0
99997    3.0
99998    3.0
99999    3.0
Name: Num_Credit_Inquiries, Length: 91518, dtype: float64

In [207]:
df.loc[:,'Changed_Credit_Limit']=df['Changed_Credit_Limit'].replace('_','',regex=True)
df['Changed_Credit_Limit'] = pd.to_numeric(df['Changed_Credit_Limit'], errors='coerce')
# df['Changed_Credit_Limit'].str.contains(r'[^a-zA-Z0-9]').sum()
df['Changed_Credit_Limit'].astype(float)

<ipython-input-207-ee75e0dcf360>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Changed_Credit_Limit'] = pd.to_numeric(df['Changed_Credit_Limit'], errors='coerce')

0        11.27
1        11.27
3         6.27
4        11.27
5         9.27
         ...
99995    11.50
99996    11.50
99997    11.50
99998    11.50
99999    11.50
Name: Changed_Credit_Limit, Length: 91518, dtype: float64

In [208]:
df['Annual_Income'] = pd.to_numeric(df['Annual_Income'], errors='coerce')
df['Num_of_Loan'] = pd.to_numeric(df['Num_of_Loan'], errors='coerce')
# df['Changed_Credit_Limit'] = pd.to_numeric(df['Changed_Credit_Limit'], errors='coerce')
df['Amount_invested_monthly'] = pd.to_numeric(df['Amount_invested_monthly'], errors='coerce')

<ipython-input-208-a8a592b0a793>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Annual_Income'] = pd.to_numeric(df['Annual_Income'], errors='coerce')
<ipython-input-208-a8a592b0a793>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Num_of_Loan'] = pd.to_numeric(df['Num_of_Loan'], errors='coerce')
<ipython-input-208-a8a592b0a793>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Amount_invested_monthly'] = pd.to_numeric(df['Amount_invested_monthly'], errors='coerce')

In [209]:
X=df.drop('Credit_Score',axis=1)
y=df['Credit_Score'].copy()

In [210]:
from  sklearn.model_selection import train_test_split

In [211]:
X

,Age,Occupation,Annual_Income,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,Changed_Credit_Limit,Num_Credit_Inquiries,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance
0,23,Scientist,19114.12,3,4,3,4,3,7.0,11.27,4.0,_,809.98,26.822620,221.0,No,49.574949,80.415295,High spent Small value payments,312.494089
1,23,Scientist,19114.12,3,4,3,4,-1,13.0,11.27,4.0,Good,809.98,31.944960,209.0,No,49.574949,118.280222,Low spent Large value payments,284.629162
3,23,Scientist,19114.12,3,4,3,4,5,4.0,6.27,4.0,Good,809.98,31.377862,224.0,No,49.574949,199.458074,Low spent Small value payments,223.451310
4,23,Scientist,19114.12,3,4,3,4,6,13.0,11.27,4.0,Good,809.98,24.797347,225.0,No,49.574949,41.420153,High spent Medium value payments,341.489231
5,23,Scientist,19114.12,3,4,3,4,8,4.0,9.27,4.0,Good,809.98,27.262259,226.0,No,49.574949,62.430172,,340.479212
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,25,Mechanic,39628.99,4,6,7,2,23,7.0,11.50,3.0,_,502.38,34.663572,316.0,No,35.104023,60.971333,High spent Large value payments,479.866228
99996,25,Mechanic,39628.99,4,6,7,2,18,7.0,11.50,3.0,_,502.38,40.565631,317.0,No,35.104023,54.185950,High spent Medium value payments,496.651610
99997,25,Mechanic,39628.99,4,6,5729,2,27,6.0,11.50,3.0,Good,502.38,41.255522,318.0,No,35.104023,24.028477,High spent Large value payments,516.809083
99998,25,Mechanic,39628.99,4,6,7,2,20,13.0,11.50,3.0,Good,502.38,33.638208,319.0,No,35.104023,251.672582,Low spent Large value payments,319.164979
99999,25,Mechanic,39628.99,4,6,7,2,18,6.0,11.50,3.0,Good,502.38,34.192463,3110.0,No,35.104023,167.163865,,393.673696

In [212]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Index: 91518 entries, 0 to 99999
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       91518 non-null  int64
 1   Occupation                91518 non-null  object
 2   Annual_Income             91518 non-null  float64
 3   Num_Bank_Accounts         91518 non-null  int64
 4   Num_Credit_Card           91518 non-null  int64
 5   Interest_Rate             91518 non-null  int64
 6   Num_of_Loan               91518 non-null  int64
 7   Delay_from_due_date       91518 non-null  int64
 8   Num_of_Delayed_Payment    91518 non-null  float64
 9   Changed_Credit_Limit      89607 non-null  float64
 10  Num_Credit_Inquiries      91518 non-null  float64
 11  Credit_Mix                91518 non-null  object
 12  Outstanding_Debt          91518 non-null  float64
 13  Credit_Utilization_Ratio  91518 non-null  float64
 14  Credit_History_Age        91518 non-null  float64
 15  Payment_of_Min_Amount     91518 non-null  object
 16  Total_EMI_per_month       91518 non-null  float64
 17  Amount_invested_monthly   91518 non-null  float64
 18  Payment_Behaviour         91518 non-null  object
 19  Monthly_Balance           91518 non-null  float64
dtypes: float64(10), int64(6), object(4)
memory usage: 14.7+ MB

In [213]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.2,stratify=y,random_state=13)

In [214]:
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing  import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

In [215]:
# X_train['Annual_Income'] #.str.extract(r'(\d+)\s*Years?\s+(\d+)\s*Months?')

In [216]:
df.dtypes

Age                           int64
Occupation                   object
Annual_Income               float64
Num_Bank_Accounts             int64
Num_Credit_Card               int64
Interest_Rate                 int64
Num_of_Loan                   int64
Delay_from_due_date           int64
Num_of_Delayed_Payment      float64
Changed_Credit_Limit        float64
Num_Credit_Inquiries        float64
Credit_Mix                   object
Outstanding_Debt            float64
Credit_Utilization_Ratio    float64
Credit_History_Age          float64
Payment_of_Min_Amount        object
Total_EMI_per_month         float64
Amount_invested_monthly     float64
Payment_Behaviour            object
Monthly_Balance             float64
Credit_Score                 object
dtype: object

re.sub(r'[^a-zA-Z0-9]', '',)
str.replace(r'[^a-zA-Z0-9]', '', regex=True)

In [217]:
num_feature= X_train.select_dtypes(include=[np.number]).columns
cat_feature= X_train.select_dtypes(exclude=[np.number]).columns

# we have outlier in Interest_Rate

In [218]:
Q1 = df['Interest_Rate'].quantile(0.25)
Q3 = df['Interest_Rate'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = (df['Interest_Rate'] < lower_bound) | (df['Interest_Rate'] > upper_bound)
df = df[~outliers]

In [219]:
cat_pipeline=Pipeline([
    ('impute',SimpleImputer(strategy='constant',fill_value='missing')),
    ('onehotencoder',OneHotEncoder(handle_unknown='ignore',sparse_output=False))
])

num_pipeline=Pipeline([
    ('impute',SimpleImputer(strategy='median')),
    ('scale',StandardScaler())
])

transformer = ColumnTransformer([
    ('num',num_pipeline,num_feature),
    ('cat',cat_pipeline,cat_feature)

],remainder='passthrough')

estimator=RandomForestClassifier()

full_pipeline = Pipeline([
    ('preprocessing', transformer),
    ('estimator',  estimator)

])

In [220]:
pd.DataFrame(transformer.fit_transform(X_train,y_train), columns = transformer.get_feature_names_out())

,num__Age,num__Annual_Income,num__Num_Bank_Accounts,num__Num_Credit_Card,num__Interest_Rate,num__Num_of_Loan,num__Delay_from_due_date,num__Num_of_Delayed_Payment,num__Changed_Credit_Limit,num__Num_Credit_Inquiries,...,cat__Payment_of_Min_Amount_NM,cat__Payment_of_Min_Amount_No,cat__Payment_of_Min_Amount_Yes,cat__Payment_Behaviour_,cat__Payment_Behaviour_High spent Large value payments,cat__Payment_Behaviour_High spent Medium value payments,cat__Payment_Behaviour_High spent Small value payments,cat__Payment_Behaviour_Low spent Large value payments,cat__Payment_Behaviour_Low spent Medium value payments,cat__Payment_Behaviour_Low spent Small value payments
0,0.650270,-0.098195,-0.093179,-0.150940,-0.116534,0.017188,-0.313100,-0.071726,0.413933,-0.121088,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,1.144844,-0.041110,-0.101653,-0.135392,-0.150668,-0.014631,-0.722241,-0.076249,-1.307264,-0.126289,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,1.144844,-0.055677,-0.101653,3.378527,-0.137868,-1.637421,-0.858622,-0.080772,-1.139049,-0.141892,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,-0.833454,-0.080846,-0.076230,-0.143166,-0.140001,-0.014631,-0.585861,-0.085295,-0.487217,-0.136691,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,-0.833454,-0.026100,-0.144025,-0.150940,-0.142135,-0.014631,0.096041,-0.103386,-0.141776,-0.131490,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73209,0.749185,-0.111682,-0.110128,-0.119844,-0.097334,0.001278,0.573373,-0.103386,0.618194,-0.095082,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
73210,0.749185,-0.117659,-0.067756,-0.135392,-0.114401,0.049008,1.596226,-0.089817,0.810439,-0.069077,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
73211,-1.525859,-0.070122,-0.076230,-0.112069,-0.101600,0.064917,1.664416,-0.076249,-1.433425,-0.089881,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
73212,-0.042135,-0.074504,-0.076230,-0.150940,-0.137868,0.017188,-0.585861,-0.094340,1.239988,-0.115887,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
73213,-0.338880,-0.114993,-0.101653,-0.135392,-0.133601,0.001278,0.300612,-0.062681,0.841980,-0.105485,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [221]:
full_pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scale',
                                                                   StandardScaler())]),
                                                  Index(['Age', 'Annual_Income', 'Num_Bank_Accounts', 'Num_Credit_Card',
       'Interest_Rate', 'Num_of_Loan', 'Delay_from_due_date',
       'Num_of_Delayed_Payment', 'Changed_Credit_Limit...
       'Credit_History_Age', 'Total_EMI_per_month', 'Amount_invested_monthly',
       'Monthly_Balance'],
      dtype='object')),
                                                 ('cat',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehotencoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  Index(['Occupation', 'Credit_Mix', 'Payment_of_Min_Amount',
       'Payment_Behaviour'],
      dtype='object'))])),
                ('estimator', RandomForestClassifier())])

In [222]:
full_pipeline.score(X_test,y_test)

0.7837631118881119

In [223]:
full_pipeline.predict(X_test.iloc[:5])

array(['Standard', 'Poor', 'Poor', 'Good', 'Standard'], dtype=object)

In [224]:
y_test[:5]

1588         Poor
28020        Poor
7229         Poor
19309        Good
30953    Standard
Name: Credit_Score, dtype: object

In [225]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_train

array([2, 0, 0, ..., 1, 2, 2])

In [226]:
y_test = encoder.fit_transform(y_test)
y_test

array([1, 1, 1, ..., 2, 2, 1])

In [227]:
%%time
full_pipeline.fit(X_train,y_train)

CPU times: user 27.8 s, sys: 110 ms, total: 27.9 s
Wall time: 28.1 s

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scale',
                                                                   StandardScaler())]),
                                                  Index(['Age', 'Annual_Income', 'Num_Bank_Accounts', 'Num_Credit_Card',
       'Interest_Rate', 'Num_of_Loan', 'Delay_from_due_date',
       'Num_of_Delayed_Payment', 'Changed_Credit_Limit...
       'Credit_History_Age', 'Total_EMI_per_month', 'Amount_invested_monthly',
       'Monthly_Balance'],
      dtype='object')),
                                                 ('cat',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehotencoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  Index(['Occupation', 'Credit_Mix', 'Payment_of_Min_Amount',
       'Payment_Behaviour'],
      dtype='object'))])),
                ('estimator', RandomForestClassifier())])

In [228]:
full_pipeline.score(X_train,y_train),full_pipeline.score(X_test,y_test)

(0.9999863414101128, 0.7832167832167832)

In [229]:
df

,Age,Occupation,Annual_Income,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,Changed_Credit_Limit,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,23,Scientist,19114.12,3,4,3,4,3,7.0,11.27,...,_,809.98,26.822620,221.0,No,49.574949,80.415295,High spent Small value payments,312.494089,Good
1,23,Scientist,19114.12,3,4,3,4,-1,13.0,11.27,...,Good,809.98,31.944960,209.0,No,49.574949,118.280222,Low spent Large value payments,284.629162,Good
3,23,Scientist,19114.12,3,4,3,4,5,4.0,6.27,...,Good,809.98,31.377862,224.0,No,49.574949,199.458074,Low spent Small value payments,223.451310,Good
4,23,Scientist,19114.12,3,4,3,4,6,13.0,11.27,...,Good,809.98,24.797347,225.0,No,49.574949,41.420153,High spent Medium value payments,341.489231,Good
5,23,Scientist,19114.12,3,4,3,4,8,4.0,9.27,...,Good,809.98,27.262259,226.0,No,49.574949,62.430172,,340.479212,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99994,25,Mechanic,39628.99,4,6,7,2,20,6.0,9.50,...,_,502.38,39.323569,315.0,No,35.104023,140.581403,High spent Medium value payments,410.256158,Poor
99995,25,Mechanic,39628.99,4,6,7,2,23,7.0,11.50,...,_,502.38,34.663572,316.0,No,35.104023,60.971333,High spent Large value payments,479.866228,Poor
99996,25,Mechanic,39628.99,4,6,7,2,18,7.0,11.50,...,_,502.38,40.565631,317.0,No,35.104023,54.185950,High spent Medium value payments,496.651610,Poor
99998,25,Mechanic,39628.99,4,6,7,2,20,13.0,11.50,...,Good,502.38,33.638208,319.0,No,35.104023,251.672582,Low spent Large value payments,319.164979,Standard
99999,25,Mechanic,39628.99,4,6,7,2,18,6.0,11.50,...,Good,502.38,34.192463,3110.0,No,35.104023,167.163865,,393.673696,Poor

In [230]:
num_feature

Index(['Age', 'Annual_Income', 'Num_Bank_Accounts', 'Num_Credit_Card',
       'Interest_Rate', 'Num_of_Loan', 'Delay_from_due_date',
       'Num_of_Delayed_Payment', 'Changed_Credit_Limit',
       'Num_Credit_Inquiries', 'Outstanding_Debt', 'Credit_Utilization_Ratio',
       'Credit_History_Age', 'Total_EMI_per_month', 'Amount_invested_monthly',
       'Monthly_Balance'],
      dtype='object')

In [231]:
cat_feature

Index(['Occupation', 'Credit_Mix', 'Payment_of_Min_Amount',
       'Payment_Behaviour'],
      dtype='object')

In [232]:
X_train.shape

(73214, 20)

In [233]:
y_train.shape

(73214,)

In [234]:
# from sklearn.ensemble import RandomForestRegressor

In [235]:
X_train_prepared=pd.DataFrame(transformer.fit_transform(X_train),columns=transformer.get_feature_names_out())
X_train_prepared

,num__Age,num__Annual_Income,num__Num_Bank_Accounts,num__Num_Credit_Card,num__Interest_Rate,num__Num_of_Loan,num__Delay_from_due_date,num__Num_of_Delayed_Payment,num__Changed_Credit_Limit,num__Num_Credit_Inquiries,...,cat__Payment_of_Min_Amount_NM,cat__Payment_of_Min_Amount_No,cat__Payment_of_Min_Amount_Yes,cat__Payment_Behaviour_,cat__Payment_Behaviour_High spent Large value payments,cat__Payment_Behaviour_High spent Medium value payments,cat__Payment_Behaviour_High spent Small value payments,cat__Payment_Behaviour_Low spent Large value payments,cat__Payment_Behaviour_Low spent Medium value payments,cat__Payment_Behaviour_Low spent Small value payments
0,0.650270,-0.098195,-0.093179,-0.150940,-0.116534,0.017188,-0.313100,-0.071726,0.413933,-0.121088,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,1.144844,-0.041110,-0.101653,-0.135392,-0.150668,-0.014631,-0.722241,-0.076249,-1.307264,-0.126289,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,1.144844,-0.055677,-0.101653,3.378527,-0.137868,-1.637421,-0.858622,-0.080772,-1.139049,-0.141892,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,-0.833454,-0.080846,-0.076230,-0.143166,-0.140001,-0.014631,-0.585861,-0.085295,-0.487217,-0.136691,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,-0.833454,-0.026100,-0.144025,-0.150940,-0.142135,-0.014631,0.096041,-0.103386,-0.141776,-0.131490,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73209,0.749185,-0.111682,-0.110128,-0.119844,-0.097334,0.001278,0.573373,-0.103386,0.618194,-0.095082,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
73210,0.749185,-0.117659,-0.067756,-0.135392,-0.114401,0.049008,1.596226,-0.089817,0.810439,-0.069077,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
73211,-1.525859,-0.070122,-0.076230,-0.112069,-0.101600,0.064917,1.664416,-0.076249,-1.433425,-0.089881,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
73212,-0.042135,-0.074504,-0.076230,-0.150940,-0.137868,0.017188,-0.585861,-0.094340,1.239988,-0.115887,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
73213,-0.338880,-0.114993,-0.101653,-0.135392,-0.133601,0.001278,0.300612,-0.062681,0.841980,-0.105485,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [236]:
X_test_prepared=pd.DataFrame(transformer.transform(X_test),columns=transformer.get_feature_names_out())
X_test_prepared

,num__Age,num__Annual_Income,num__Num_Bank_Accounts,num__Num_Credit_Card,num__Interest_Rate,num__Num_of_Loan,num__Delay_from_due_date,num__Num_of_Delayed_Payment,num__Changed_Credit_Limit,num__Num_Credit_Inquiries,...,cat__Payment_of_Min_Amount_NM,cat__Payment_of_Min_Amount_No,cat__Payment_of_Min_Amount_Yes,cat__Payment_Behaviour_,cat__Payment_Behaviour_High spent Large value payments,cat__Payment_Behaviour_High spent Medium value payments,cat__Payment_Behaviour_High spent Small value payments,cat__Payment_Behaviour_Low spent Large value payments,cat__Payment_Behaviour_Low spent Medium value payments,cat__Payment_Behaviour_Low spent Small value payments
0,-0.833454,-0.096382,-0.101653,-0.135392,2.223786,-0.030541,-0.654051,-0.107909,-1.232168,-0.136691,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,1.045929,-0.113090,-0.067756,-0.096521,-0.097334,0.017188,0.982514,-0.098863,-0.087707,-0.095082,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,-1.328029,-0.101595,-0.067756,-0.104295,-0.120801,0.001278,0.096041,-0.026498,-0.141776,-0.095082,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,-1.328029,-0.113134,-0.127076,-0.166488,-0.148535,-0.046451,-0.995002,-0.130523,-0.795110,-0.126289,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1.441589,-0.014530,-0.144025,-0.143166,-0.137868,-0.030541,-0.858622,-0.126000,-1.353823,-0.121088,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18299,0.155695,-0.052873,-0.093179,-0.119844,-0.144268,-0.014631,0.505183,-0.067204,-0.638911,-0.136691,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
18300,0.254610,-0.106044,-0.118602,-0.119844,-0.142135,0.017188,0.164232,-0.085295,0.556615,-0.100284,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
18301,-1.525859,-0.040857,-0.093179,-0.143166,-0.133601,-0.046451,0.096041,-0.080772,-1.086482,-0.136691,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
18302,0.353525,-0.118659,-0.101653,-0.119844,-0.129334,0.049008,0.641563,-0.071726,1.170900,-0.105485,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
18303,0.155695,-0.116855,-0.076230,-0.119844,-0.084533,0.033098,0.027851,-0.062681,1.098808,-0.110686,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [237]:
from sklearn.linear_model import LinearRegression

In [238]:
# full_pipeline = Pipeline(steps=[
#     ('preprocessor', transformer),
#     ('model', LinearRegression()) ])

# full_pipeline.fit(X_train, y_train)

In [239]:
y_test

array([1, 1, 1, ..., 2, 2, 1])

In [240]:
from sklearn.linear_model import LinearRegression

lin_reg =LinearRegression()
lin_reg.fit(X_train_prepared,y_train)
lin_reg.score(X_test_prepared, y_test)

0.1764558228994394

In [241]:
lin_reg.predict(X_test_prepared.iloc[:5])

array([0.86615354, 1.68163488, 1.37052443, 0.85145585, 0.86211832])

In [242]:
y_test[:5]

array([1, 1, 1, 0, 2])

In [243]:
!free -h

               total        used        free      shared  buff/cache   available
Mem:            12Gi       2.9Gi       6.2Gi       2.0Mi       3.6Gi       9.5Gi
Swap:             0B          0B          0B

In [244]:
df.isna().sum()

Age                            0
Occupation                     0
Annual_Income                  0
Num_Bank_Accounts              0
Num_Credit_Card                0
Interest_Rate                  0
Num_of_Loan                    0
Delay_from_due_date            0
Num_of_Delayed_Payment         0
Changed_Credit_Limit        1863
Num_Credit_Inquiries           0
Credit_Mix                     0
Outstanding_Debt               0
Credit_Utilization_Ratio       0
Credit_History_Age             0
Payment_of_Min_Amount          0
Total_EMI_per_month            0
Amount_invested_monthly        0
Payment_Behaviour              0
Monthly_Balance                0
Credit_Score                   0
dtype: int64

In [245]:
df.duplicated().sum()

0